### ISSUE TITLE
[question] Is there an elegant way to pass a script tag with a component?

### ISSUE THREAD

**Issue by matejukmar** [kitajs/html#62] opened 2023-11-06 18:00 UTC
I did some tests and tried to pass a script tag inside a component. It seems it strips out the curly brackets from within the tag:

`<script>function click(){console.log('test')}</script>` transformed to `<script>function click()</script>`

but this worked:

`<script>{"function click(){console.log('test')}"}</script>`

But in both cases there was no syntax highlighting... I'm just exploring the prospects of getting rid of React for my next project and this library seems to be very promising approach.

**Comment by arthurfiorette** [comment] 2023-11-06 18:59
Duplicate of https://github.com/kitajs/html/issues/53

**Closed by arthurfiorette** 2023-11-06 18:59 UTC
